CREATE TABLE products (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255),
	product_type ENUM('BOLSA','JOGO_DE_BANHEIRO','KIT_BANDEJA','KIT_ORGANIZADOR','ROUPA','TAPETE') DEFAULT NULL,
	created_at DATETIME DEFAULT NULL,
	updated_at DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
