CREATE TABLE event_images (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	image_url VARCHAR(255) NOT NULL,
	file_name VARCHAR(255) DEFAULT NULL,
	file_size BIGINT DEFAULT NULL,
	file_type VARCHAR(255) DEFAULT NULL,
	event_id BIGINT NOT NULL,
	created_at DATETIME DEFAULT NULL,
	updated_at DATETIME DEFAULT NULL,

	CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;